version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_DB: task_board_dev
      POSTGRES_PASSWORD: secret123
    ports:
      - 5432:5432

  test-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_DB: task_board_test
      POSTGRES_PASSWORD: secret123
    ports:
      - 5434:5432

  prod-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_DB: task_board_prod
      POSTGRES_PASSWORD: JK-_132H213kjdSDdTTdsa
    ports:
      - 40566:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
